name: Build and Deploy Docker Image
on: 
  push:
    branches:
      - '**'
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Chechout code
    uses: actions/checkout@v3

    - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

    -name: Build Docker Image
    run:
    docker build -t course_project:latest go/.

    - name: Run Docker Container
    run:
    docker run -d -p 8888:8888 course_project:latest
